# Generated by Django 4.0.1 on 2022-01-27 11:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('first_name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Kategoria')),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Instytucja')),
                ('description', models.TextField(max_length=1000, verbose_name='Opis')),
                ('type', models.IntegerField(choices=[(1, 'fundacja'), (2, 'organizacja pozarządowa'), (3, 'zbiórka lokalna')], verbose_name='Typ')),
                ('categories', models.ManyToManyField(to='main.Category', verbose_name='Kategoria')),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Ilość')),
                ('address', models.CharField(max_length=100, verbose_name='Adres')),
                ('phone_number', models.IntegerField(verbose_name='Numer telefonu')),
                ('city', models.CharField(max_length=100, verbose_name='Miasto')),
                ('zip_code', models.CharField(max_length=6, verbose_name='Kod pocztowy')),
                ('pick_up_date', models.DateField(verbose_name='Data odbioru')),
                ('pick_up_time', models.TimeField(verbose_name='Godzina odbioru')),
                ('pick_up_comment', models.TextField(max_length=1000, verbose_name='Komentarz')),
                ('categories', models.ManyToManyField(to='main.Category', verbose_name='Kategoria')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.institution', verbose_name='Instytucja')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik')),
            ],
        ),
    ]
