# Generated by Django 4.0.1 on 2022-01-17 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Instytucja')),
                ('description', models.TextField(verbose_name='Opis')),
                ('type', models.IntegerField(choices=[(1, 'fundacja'), (2, 'organizacja pozarządowa'), (3, 'zbiórka lokalna')], verbose_name='Typ')),
                ('categories', models.ManyToManyField(to='main.Category', verbose_name='Kategoria')),
            ],
        ),
    ]
