# Generated by Django 4.0.1 on 2022-01-18 12:57

from django.db import migrations
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='myuser',
            managers=[
                ('objects', main.models.UserManager()),
            ],
        ),
    ]
