# Generated by Django 4.0.1 on 2022-01-17 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_institution_description_donation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='phone_number',
            field=models.IntegerField(verbose_name='Numer telefonu'),
        ),
    ]
